### ISSUE TITLE
Ability to import CSV users to course

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#103]
- [x] required fields: email, name (or first name + last name)
- [x] (optional) it would be good to have a page where they can map fields from CSV to ours
- [x] during import we need to create a new Laravel job (not real time) to do the following:
- [x] create user account
- [x] enrol user to this course
- [x] generate random password for each user and send them email with information about enrolled course, instructor and temporary password

Lets create a new Students tab for this:
![2018-08-02_15-24-20](https://user-images.githubusercontent.com/1173105/43606209-b3ca956c-9668-11e8-87b7-a592b5ce7b46.png)

**Comment by kurumbus** [comment]
@websquared  will start tomorrow

**Comment by kurumbus** [comment]
@websquared to enroll a user you need to specify a payment_method. 
I was thinking about something like "manual" or "imported" because we should not include imported users in buy_now and subscription lists when eventually we will need to create some sales statistic. 

What do you think?

**Comment by kurumbus** [comment]
Note to myself:
- [ ] Validation of required fields
- [ ] Add key to jobs
- [ ] Send report to the manager
- [ ] Better invite email

**Comment by websquared** [comment]
Yes, I agree. Let’s add “manual” method

**Comment by kurumbus** [comment]
Finishing up this one, testing the whole system

**Comment by kurumbus** [comment]
- [ ] Better progress report

**Comment by websquared** [comment]
Thanks. Will test it as well

**Comment by kurumbus** [comment]
@Alinlish That's the new feature, could you test it? 

In short: an instructor or manager can now import users from CSV file.
I think we should add some hints, but I'm not sure which since I've done it. Could you suggest something?

**Comment by Alinlish** [comment]
My comments:
1. It's not clear why the links to "WebinarJam, Livestorm" are added, because they are not helpful for user (they seem complicated) [Link](https://www.screencast.com/t/v0vq30fD).
2. When trying to import students with fields email and name (email with wrong format) as in [file](https://www.screencast.com/t/uHprGp5w1Ryw), the message that the student are imported is displayed [Link](https://www.screencast.com/t/JG5RHz1Su), but no student is imported [Link](https://www.screencast.com/t/kfpl17c8a)
3. When trying to import students with fields email, name (email with correct format) and other as in file [Link](https://www.screencast.com/t/iiStuL4G), the message that the import is in progress is displayed, but no student is actually imported [Link](https://www.screencast.com/t/ea098hlPpvQ)
4. When no fields are selected [Link](https://www.screencast.com/t/sGmm0u3kT4rM), the successful message is displayed. After that, if clicking on other tab (example Instructor), an error page is displayed [Link](https://www.screencast.com/t/Zvr4HfG5Qvar)
5. An error page is displayed and the page is continuously loading when trying to upload another type of file (example pdf) [Link](https://www.screencast.com/t/wMaUF50XH7y)
6. When importing students with fields name or email added twice [Link](https://www.screencast.com/t/xCOElq79OnJ), an error page is displayed [Link](https://www.screencast.com/t/DWxhxgCqI7h)
7. My suggestion is to add one downloadable file as example, completed with one line for all fields, just for the user to see how to complete fields. Also, he can remove fields not necessary, and keep only what he wants.
8. When importing one empty file, it would be good to remove the drop-down which is not needed [Link](https://www.screencast.com/t/L0xpj9IQRf1)

**Comment by kurumbus** [comment]
(For myself)

Code-related bugs: 
- [ ] 2. When trying to import students with fields email and name (email with wrong format) as in file, the message that the student are imported is displayed Link, but no student is imported Link
- [ ] 4. When no fields are selected Link, the successful message is displayed. After that, if clicking on other tab (example Instructor), an error page is 
- [ ] 5. An error page is displayed and the page is continuously loading when trying to upload another type of file (example pdf) 
- [ ] 6. When importing students with fields name or email added twice Link, an error page is displayed Link
- [ ] 8. When importing one empty file, it would be good to remove the drop-down which is not needed Link

Environment-related bugs (seems like)
- [ ] 3.When trying to import students with fields email, name (email with correct format) and other as in file Link, the message that the import is in progress is displayed, but no student is actually imported Link

UI:
- [ ] 1. It's not clear why the links to "WebinarJam, Livestorm" are added, because they are not helpful for user (they seem complicated) 
- [ ] 7. My suggestion is to add one downloadable file as example, completed with one line for all fields, just for the user to see how to complete fields. Also, he can remove fields not necessary, and keep only what he wants.
