### ISSUE TITLE
Import users page bugs

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#111]
- [x] Display error message if no file selected (or disable button)
- [x] During import:
![2018-08-07_17-19-27](https://user-images.githubusercontent.com/1173105/43804029-abf3567c-9a68-11e8-8b15-2b59f0f9d4b8.png)
- [x] Create ability to combine first_name, last_name into our name field

**Comment by kurumbus** [comment]
@websquared It does combine fields already. The only limitation is it combines them in alphabetical order. I thought it's OK for now, because first_name is alpabetically before last_name and same for address_line_1 and address_line_2 and such fields with numeric prefixes.  If we let the user specify order - how to do it in the UI? I have no idea on the spot.

About the bug: so sorry, forgot to fix that one before PR, it's a known one.

**Comment by kurumbus** [comment]
I'll write Alin on how to test it in #103 but these particular bugs should be fixed

**Comment by websquared** [comment]
I'll remove checkboxes for steps 5 and 6 completely because they are optional
