### ISSUE TITLE
Proposal: resources catalog

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#44]
_From @kurumbus on June 24, 2018 18:45_

We are kind of already storing all our resources in one table, so it should be rather easy to
1. Create a page with a list of resources (perhaps some filtering, but not necessarily)
2. When instructor or manager is attaching resources - to let him choose from existing ones

![online courses acme inc 1](https://user-images.githubusercontent.com/13556916/41822417-e2598f9e-77f7-11e8-9c38-a13d3f684fa0.png)

_Copied from original issue: websquared/learnformula-cloud#228_

**Comment by websquared** [comment]
Adding to TODO

**Comment by kurumbus** [comment]
@Alinlish Could you test this one? 

The deal is: you can add resources at one place:
like https://acme.learnformula.space/course-activities/5/edit

and access them at other: like landing page, another course activity.

One note: I've added some checks to prevent duplication, but if you really want to, you can get around them and wind up with several identical resources in the catalog. Don't know if we should spend time to fix that.

**Comment by Alinlish** [comment]
My comments:
1. I added few resources (both files and externals) and now the resource catalog is not displayed. Also, nothing happens when I try to use the filter by title [Link](https://www.screencast.com/t/iDPhjRE7Pl).
2. When adding a new resource as file (in this case pdf), an error message is displayed [Link](https://www.screencast.com/t/5fPJwkfakim)
3. After adding a new external resource, the title is removed, but the link is kept [Link](https://www.screencast.com/t/lkVboxXx)

**Comment by kurumbus** [comment]
- [ ] 1. I added few resources (both files and externals) and now the resource catalog is not displayed. 1.1 Also, nothing happens when I try to use the filter by title Link.
When adding a new resource as file (in this case pdf), an error message is displayed Link
After adding a new external resource, the title is removed, but the link is kept Link

**Comment by kurumbus** [comment]
fixed everything i could reproduce
