### ISSUE TITLE
When resizing, homepage breaks

### ISSUE THREAD

**Issue by mkatsevman** [websquared/lfc#79]
https://prnt.sc/k415gr

**Comment by websquared** [comment]
@polis89 any updates on this?

**Comment by websquared** [comment]
@polis89 
Let's also organize our CSS files:

- [ ] Move any homepage related CSS from resources/assets/sass/app.scss to public/css/homepage.css file (included only on homepage). All the styles that you made for homepage are not used anywhere else.
- [ ] If you need to change or add something to Semantic UI SASS - do that in separate file resources/assets/sass/semantic-ext.scss instead of app.scss (it's imported there anyway)
- [ ] Let's keep app.scss as clean and small as possible
